// The app's illustrative layer — BOTH modes.
//
// Most of this file is the hand-drawn die-cut sticker cast (personalized only).
// It also holds the two things that had to live somewhere shared: the paper
// note stack that replaces the sticker character in professional mode, and
// `flashComplete`, the completion mark, which is drawn by every surface that
// owns a checkbox.
//
// Hand-drawn die-cut sticker characters.
//
// These deliberately sit OUTSIDE the theme token system — the colours are
// hard-coded so the stickers stay exactly as warm and colourful in light mode
// as in dark. They are the one place in the app that breaks the design system
// on purpose: they should feel drawn by a person and stuck onto the timeline,
// not generated by it.
//
// Every character takes `hovered` and nudges one or two of its own details in
// response, so the reaction feels characterful rather than a generic scale-up.

import { useState } from 'react'
import { motion } from 'framer-motion'

// The completion mark drawn INSIDE a checkbox (both modes). When `completing`,
// the circle fills green and the tick strokes itself on in place — so the
// animation is part of the checkbox rather than a separate overlay pasted on
// top. Renders nothing while empty (the button's own border is the circle).
export function CheckMark({ done = false, completing = false }) {
  const filled = done || completing
  if (!filled) return null
  return (
    <svg viewBox="0 0 24 24" className="absolute inset-0 h-full w-full" aria-hidden="true">
      <motion.circle
        cx="12" cy="12" r="12" fill="var(--success)"
        initial={completing ? { scale: 0.2, opacity: 0.4 } : false}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: completing ? 0.2 : 0, ease: [0.22, 0.61, 0.36, 1] }}
        style={{ transformOrigin: '12px 12px' }}
      />
      <motion.path
        d="M6.4 12.5 L10.4 16.3 L17.6 8"
        fill="none" stroke="#06281c" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"
        initial={completing ? { pathLength: 0 } : { pathLength: 1 }}
        animate={{ pathLength: 1 }}
        transition={{ duration: completing ? 0.26 : 0, ease: 'easeOut', delay: completing ? 0.08 : 0 }}
      />
    </svg>
  )
}

const CREAM = '#FFF8EE'
const BLUSH = '#F58FA8'

// shared: thick cream underlay = the die-cut edge, drawn beneath the fill
function DieCut({ d, fill, ink, strokeWidth = 2.6 }) {
  return (
    <>
      <path d={d} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
      <path d={d} fill={fill} stroke={ink} strokeWidth={strokeWidth} strokeLinejoin="round" />
    </>
  )
}

const ease = 'transform .45s cubic-bezier(0.34, 1.56, 0.64, 1)'

export function SleepyBlob({ size = 84, hovered = false }) {
  const body = 'M34 10c10-1 20 5 23 14 3 10-2 21-11 26-9 5-21 3-27-4-6-7-7-19-1-27 4-6 10-8 16-9z'
  return (
    <svg viewBox="0 0 76 66" width={size} height={size * 0.87} aria-hidden="true">
      <g transform="rotate(-7 36 34)">
        <DieCut d={body} fill="#B9A7F0" ink="#2E2A33" />
        <ellipse cx="22" cy="38" rx="5" ry="3.2" fill={BLUSH} opacity=".6" />
        <ellipse cx="49" cy="38" rx="5" ry="3.2" fill={BLUSH} opacity=".6" />
        <path d="M21 31q4.5 5 9 0" fill="none" stroke="#2E2A33" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M41 31q4.5 5 9 0" fill="none" stroke="#2E2A33" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M32 40q4 3.5 8 0" fill="none" stroke="#2E2A33" strokeWidth="2.4" strokeLinecap="round" />
      </g>
      {/* the z's drift up when you look at it */}
      <g style={{ transform: hovered ? 'translate(2px,-5px)' : 'none', transition: ease }}>
        <path d="M60 20h7l-7 8h7" fill="none" stroke="#B9A7F0" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M64 7h5l-5 6h5" fill="none" stroke="#B9A7F0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity=".65" />
      </g>
    </svg>
  )
}

export function Snail({ size = 92, hovered = false }) {
  const foot = 'M8 47c0-7 5-11 12-11h30c5 0 9 2 9 5s-4 6-9 6H8z'
  return (
    <svg viewBox="0 0 78 60" width={size} height={size * 0.77} aria-hidden="true">
      {/* the whole snail inches forward */}
      <g transform="rotate(3 39 30)" style={{ transform: hovered ? 'translateX(3px)' : 'none', transition: ease }}>
        <DieCut d={foot} fill="#7FD8A8" ink="#26332C" />
        <circle cx="29" cy="26" r="15" fill={CREAM} stroke={CREAM} strokeWidth="9" />
        <circle cx="29" cy="26" r="15" fill="#F5D06B" stroke="#26332C" strokeWidth="2.6" />
        <path d="M29 26a5 5 0 1 1 5-5 9.5 9.5 0 1 1-9.5 9.5" fill="none" stroke="#26332C" strokeWidth="2.2" strokeLinecap="round" />
        <path d="M53 37l2-9M59 38l6-7" stroke="#26332C" strokeWidth="2.4" strokeLinecap="round" />
        <circle cx="55.5" cy="26" r="2.7" fill="#26332C" />
        <circle cx="66" cy="30" r="2.7" fill="#26332C" />
        <path d="M52 43q3.5 2.5 7 0" fill="none" stroke="#26332C" strokeWidth="2.2" strokeLinecap="round" />
      </g>
    </svg>
  )
}

export function CatLoaf({ size = 84, hovered = false }) {
  const loaf = 'M8 49c0-14 9-23 26-23s26 9 26 23z'
  const ears = 'M15 33l1-12 10 7zM53 33l-1-12-10 7z'
  return (
    <svg viewBox="0 0 72 60" width={size} height={size * 0.83} aria-hidden="true">
      <g transform="rotate(-4 36 30)">
        {/* papers it is sitting on — the tail flicks over them */}
        <g style={{ transform: hovered ? 'rotate(-7deg)' : 'none', transformOrigin: '44px 48px', transition: ease }}>
          <path d="M42 50h16l-4-7h-14z" fill={CREAM} stroke={CREAM} strokeWidth="7" />
          <path d="M42 50h16l-4-7h-14z" fill="#F0EAD8" stroke="#33302A" strokeWidth="2.2" strokeLinejoin="round" />
        </g>
        <path d={ears} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
        <path d={loaf} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
        <path d={ears} fill="#F5B06B" stroke="#33302A" strokeWidth="2.5" strokeLinejoin="round" />
        <path d={loaf} fill="#F5B06B" stroke="#33302A" strokeWidth="2.6" strokeLinejoin="round" />
        <path d="M21 39q4 4.5 8 0M39 39q4 4.5 8 0" fill="none" stroke="#33302A" strokeWidth="2.5" strokeLinecap="round" />
        <path d="M34 43l-2.5 3h5z" fill={BLUSH} stroke="#33302A" strokeWidth="1.6" strokeLinejoin="round" />
        <path d="M12 41H4M12 46l-8 2M56 41h8M56 46l8 2" stroke="#33302A" strokeWidth="1.8" strokeLinecap="round" opacity=".8" />
      </g>
    </svg>
  )
}

export function Ghost({ size = 78, hovered = false }) {
  const body = 'M13 49V27a19 19 0 0 1 38 0v22l-6.3-5.3-6.4 5.3-6.3-5.3-6.4 5.3z'
  return (
    <svg viewBox="0 0 64 62" width={size} height={size * 0.97} aria-hidden="true">
      {/* bobs up when noticed */}
      <g transform="rotate(5 32 31)" style={{ transform: hovered ? 'translateY(-4px)' : 'none', transition: ease }}>
        <DieCut d={body} fill="#8FC7F5" ink="#25303B" />
        <circle cx="25" cy="28" r="3.1" fill="#25303B" />
        <circle cx="40" cy="28" r="3.1" fill="#25303B" />
        <ellipse cx="19" cy="35" rx="4.2" ry="2.7" fill={BLUSH} opacity=".6" />
        <ellipse cx="46" cy="35" rx="4.2" ry="2.7" fill={BLUSH} opacity=".6" />
        <path d="M29 35q3.5 3.5 7 0" fill="none" stroke="#25303B" strokeWidth="2.3" strokeLinecap="round" />
      </g>
    </svg>
  )
}

export function PartyBean({ size = 92, hovered = false }) {
  const body = 'M38 14c11 0 19 8 19 19s-8 20-19 20-19-9-19-20 8-19 19-19z'
  return (
    <svg viewBox="0 0 78 66" width={size} height={size * 0.85} aria-hidden="true">
      <g style={{ transform: hovered ? 'scale(1.12)' : 'none', transformOrigin: '39px 20px', transition: ease }}>
        <path d="M20 8l-3 7M60 12l5-5M68 30l7 1M12 26l-7-2" stroke={BLUSH} strokeWidth="2.6" strokeLinecap="round" />
        <rect x="58" y="44" width="7" height="7" rx="1.5" fill="#7FD8A8" transform="rotate(25 61 47)" />
        <rect x="10" y="42" width="6" height="6" rx="1.5" fill="#8FC7F5" transform="rotate(-20 13 45)" />
      </g>
      <g transform="rotate(-5 39 36)">
        <DieCut d={body} fill={BLUSH} ink="#3B2630" />
        <path d="M28 30q3.5-5 7 0M42 30q3.5-5 7 0" fill="none" stroke="#3B2630" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M31 38q7 7 14 0" fill="none" stroke="#3B2630" strokeWidth="2.6" strokeLinecap="round" />
        <ellipse cx="25" cy="37" rx="4" ry="2.6" fill="#E0683C" opacity=".5" />
        <ellipse cx="51" cy="37" rx="4" ry="2.6" fill="#E0683C" opacity=".5" />
      </g>
    </svg>
  )
}

export function HappyStar({ size = 88, hovered = false }) {
  const body = 'M35 8l8 16 18 2-13 12 4 18-17-9-17 9 4-18L9 26l18-2z'
  return (
    <svg viewBox="0 0 70 66" width={size} height={size * 0.94} aria-hidden="true">
      <g transform="rotate(6 35 34)" style={{ transform: hovered ? 'rotate(14deg)' : 'none', transformOrigin: '35px 34px', transition: ease }}>
        <path d={body} fill={CREAM} stroke={CREAM} strokeWidth="10" strokeLinejoin="round" />
        <path d={body} fill="#F5D06B" stroke="#3A3320" strokeWidth="2.6" strokeLinejoin="round" />
        <circle cx="28" cy="31" r="2.8" fill="#3A3320" />
        <circle cx="42" cy="31" r="2.8" fill="#3A3320" />
        <path d="M30 38q5 5 10 0" fill="none" stroke="#3A3320" strokeWidth="2.4" strokeLinecap="round" />
        <ellipse cx="23" cy="37" rx="3.6" ry="2.3" fill={BLUSH} opacity=".55" />
        <ellipse cx="47" cy="37" rx="3.6" ry="2.3" fill={BLUSH} opacity=".55" />
      </g>
    </svg>
  )
}

// Waiting-pile cast. Order is stable — a pile hashes its day key into this
// array so the same day always gets the same character (it should read as
// someone who showed up, not a random shuffle every render).
export const WAITING = [
  { Art: SleepyBlob, rest: -7, label: 'napping' },
  { Art: Snail, rest: 3, label: 'taking their time' },
  { Art: CatLoaf, rest: -4, label: 'under the cat' },
  { Art: Ghost, rest: 5, label: 'gently haunting' },
]

// A per-session salt so the cast actually rotates on reload/reopen. Hashing the
// day key alone meant a given day ALWAYS drew the same character — stable, but
// in practice you only ever saw one of them. The salt is fixed for the life of
// the tab, so a character still can't shuffle out from under you mid-session.
const SESSION_SALT = Math.floor(Math.random() * WAITING.length)

export function pickWaiting(seed = '') {
  let h = 0
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0
  return WAITING[(h + SESSION_SALT) % WAITING.length]
}

const prefersReduced = () =>
  typeof window !== 'undefined' &&
  window.matchMedia?.('(prefers-reduced-motion: reduce)').matches

// ---------------------------------------------------------------------------
// PROFESSIONAL: the paper note stack.
//
// Same job as the sticker — hold the overflow the cap hides and offer the
// escape valve in one tap — with no character in it. Three real notes, each
// with its own edge and shadow; the top one carries the count. Rest / fan on
// hover / tilt-and-sweep when cleared, all in CSS (see .note-stack).
// ---------------------------------------------------------------------------
export function PaperNoteStack({ count = 0, label, calm = false, width = 128, height = 40, onClick, title }) {
  const still = calm || prefersReduced()

  // Click just fires onClick (which now EXPANDS the pile). The old tilt-away
  // sweep was for the bump action; the pile no longer bumps on click, so
  // sweeping it away here would fight the expand.
  return (
    <button
      type="button"
      onClick={() => onClick?.()}
      title={title}
      aria-label={title}
      className={`note-stack${still ? ' calm' : ''}`}
      style={{ '--ns-w': `${width}px`, '--ns-h': `${height}px` }}
    >
      <span className="note n-3" aria-hidden="true"><span className="n-lines"><i /><i /></span></span>
      <span className="note n-2" aria-hidden="true"><span className="n-lines"><i /><i /></span></span>
      <span className="note n-1"><span className="n-count">{label ?? count}</span></span>
    </button>
  )
}

// ---------------------------------------------------------------------------
// The completion mark.
//
// It is spawned into <body> imperatively instead of rendered inside the task,
// because completing a task UNMOUNTS its bar (dayBands moves it straight to
// `completed`) — a mark drawn inside the bar gets cut off mid-stroke.
//
// Driven by rAF writing attributes, NOT by a CSS/WAAPI animation: it has to
// advance in a harness that freezes document.timeline, and it must never lean
// on React state (Constitution III). The SVG is built once; only attributes
// change per frame.
//
//   professional — Apple-Pay: ring sweeps, disc fills, check draws, 3% settle.
//   personalized — the same beat, drawn scratchily stroke by stroke.
// ---------------------------------------------------------------------------
const RING_LEN = 131.95 // 2πr, r = 21
const CHK_LEN = 27.4
const easeOut = (x) => 1 - Math.pow(1 - x, 3)
const seg = (t, a, b) => (t <= a ? 0 : t >= b ? 1 : easeOut((t - a) / (b - a)))

const AP_SVG = `<svg viewBox="0 0 48 48" width="100%" height="100%" style="display:block;transform-origin:50% 50%">
  <circle cx="24" cy="24" r="21" fill="var(--success)" opacity="0"/>
  <circle cx="24" cy="24" r="21" fill="none" stroke="var(--success)" stroke-width="3" stroke-linecap="round"
    stroke-dasharray="${RING_LEN}" stroke-dashoffset="${RING_LEN}" transform="rotate(-90 24 24)"/>
  <path d="M15 24.5 L21.5 31 L33.5 17.5" fill="none" stroke="#0d2b21" stroke-width="3.6"
    stroke-linecap="round" stroke-linejoin="round"
    stroke-dasharray="${CHK_LEN}" stroke-dashoffset="${CHK_LEN}"/>
</svg>`

const SCRATCH_SVG = `<svg viewBox="0 0 24 24" width="100%" height="100%" style="display:block;transform-origin:50% 50%">
  <path d="M4.5 12.8 C 6.4 14.2, 8.1 16.1, 9.6 18.2" fill="none" stroke="var(--success)" stroke-width="2.9"
    stroke-linecap="round" stroke-dasharray="9" stroke-dashoffset="9"/>
  <path d="M9.6 18.2 C 12.6 13.4, 16.1 9.1, 20 5.6" fill="none" stroke="var(--success)" stroke-width="2.9"
    stroke-linecap="round" stroke-dasharray="18" stroke-dashoffset="18"/>
  <path d="M5.6 13.6 C 7.2 15.2, 8.4 16.6, 9.4 17.9" fill="none" stroke="var(--success)" stroke-width="1"
    stroke-linecap="round" opacity="0"/>
</svg>`

const DUR = 620
const HOLD = 240
const FADE = 220

export function flashComplete(anchor, { personalized = false, calm = false } = {}) {
  if (typeof document === 'undefined' || !anchor?.getBoundingClientRect) return
  const r = anchor.getBoundingClientRect()
  if (!r.width) return
  const size = personalized ? 30 : 32
  const host = document.createElement('div')
  host.setAttribute('aria-hidden', 'true')
  host.style.cssText =
    `position:fixed;left:${r.left + r.width / 2 - size / 2}px;top:${r.top + r.height / 2 - size / 2}px;` +
    `width:${size}px;height:${size}px;z-index:80;pointer-events:none`
  host.innerHTML = personalized ? SCRATCH_SVG : AP_SVG
  document.body.appendChild(host)

  const svg = host.firstElementChild
  const [a, b, c] = svg.children
  const still = calm || prefersReduced()

  const draw = (t) => {
    if (personalized) {
      a.setAttribute('stroke-dashoffset', ((1 - seg(t, 0.08, 0.52)) * 9).toFixed(2))
      b.setAttribute('stroke-dashoffset', ((1 - seg(t, 0.42, 0.94)) * 18).toFixed(2))
      c.setAttribute('opacity', (seg(t, 0.5, 1) * 0.55).toFixed(3))
      svg.style.transform = `scale(${(0.8 + 0.2 * seg(t, 0, 0.35)).toFixed(3)})`
    } else {
      a.setAttribute('opacity', seg(t, 0.24, 0.53).toFixed(3))
      b.setAttribute('stroke-dashoffset', ((1 - seg(t, 0, 0.31)) * RING_LEN).toFixed(2))
      c.setAttribute('stroke-dashoffset', ((1 - seg(t, 0.45, 0.84)) * CHK_LEN).toFixed(2))
      // a 3% settle at the tail — a scale-down to rest, never an overshoot
      svg.style.transform = `scale(${(t < 0.84 ? 1 : 1.03 - 0.03 * seg(t, 0.84, 1)).toFixed(3)})`
    }
  }

  const done = () => host.remove()
  if (still) {
    draw(1)
    setTimeout(done, 420)
    return
  }

  draw(0)
  const t0 = performance.now()
  let raf = 0
  const tick = (now) => {
    const e = now - t0
    const t = Math.min(1, e / DUR)
    draw(t)
    if (e > DUR + HOLD) host.style.opacity = String(Math.max(0, 1 - (e - DUR - HOLD) / FADE))
    if (e >= DUR + HOLD + FADE) { done(); return }
    raf = requestAnimationFrame(tick)
  }
  raf = requestAnimationFrame(tick)
  // rAF stops in a backgrounded tab; without this the node would linger forever
  setTimeout(() => { cancelAnimationFrame(raf); done() }, DUR + HOLD + FADE + 900)
}

// ---------------------------------------------------------------------------
// The hand-drawn details (personalized only — each is rendered inside a
// .craft-only wrapper or gated by [data-mode='personalized'] in index.css).
// ---------------------------------------------------------------------------

// #2 — the Completed drawer tears off the column instead of ending on a rule.
// One deterministic path: it should look torn once, not restless.
export function TearEdge() {
  // A soft, rolling torn edge — smooth curves rather than a sawtooth, matching
  // the approved rendering where the drawer bottom looks like torn paper, not a
  // zigzag. Two overlaid waves give it a little irregularity.
  return (
    <svg className="tear-edge craft-only" viewBox="0 0 200 10" preserveAspectRatio="none" aria-hidden="true">
      <path
        d="M0 5
           C 10 2, 18 2, 26 5 S 42 8, 52 5 S 68 2, 78 5.5 S 96 8, 106 4.5
           S 122 2, 132 5 S 150 8, 160 4.5 S 178 2, 188 5 S 197 6.5, 200 5
           L200 10 L0 10 Z"
        fill="currentColor"
      />
    </svg>
  )
}

// #1 — the scratchy checkbox. Personalized only. Empty reads as a hand-drawn
// coral square; done fills green and a check strokes itself on (CSS drives the
// dash so it survives the preview's frozen animation clock). The completing
// component still calls flashComplete for the burst; this is the resting mark.
export function ScratchCheck({ done = false, size = 22 }) {
  return (
    <svg
      className={`scratch-check ${done ? 'is-done' : ''}`}
      width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"
    >
      {/* wobbly rounded square — not a perfect rect, drawn like by hand */}
      <path
        className="sc-box"
        d="M5.5 3.2 C 9 2.6, 15 2.8, 18.6 3.4 C 21 3.8, 21.4 6, 21 9
           C 20.7 13, 21.2 17.5, 20.4 19.8 C 20 21.2, 17 21.2, 12.5 21.2
           C 8 21.2, 4.2 21.3, 3.2 19.6 C 2.4 18, 2.7 13, 2.8 9
           C 2.9 5.5, 3 3.8, 5.5 3.2 Z"
        fill="none" strokeWidth="2.1" strokeLinecap="round" strokeLinejoin="round"
      />
      {/* the tick, drawn on stroke-by-stroke via dashoffset when .is-done */}
      <path
        className="sc-tick"
        d="M6.5 12.4 L10.6 16.6 L18 7.4"
        fill="none" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"
      />
    </svg>
  )
}

// #4 — page-corner fold: the column turns up its own corner when there is more
// below the fold. Visibility is driven by `.has-more` on the parent.
export function CornerFold() {
  return (
    <svg className="corner-fold craft-only" viewBox="0 0 34 34" aria-hidden="true">
      <path d="M34 4 L34 34 L4 34 Z" fill="var(--bg)" />
      <path d="M34 4 C 25 11, 16 21, 4 34" fill="none" stroke="var(--ink)" strokeWidth="2" opacity=".9" />
      <path d="M34 4 C 27 8, 20 15, 13 23" fill="none" stroke="var(--text-faint)" strokeWidth="1.1" opacity=".55" />
      <path d="M31 9 C 25 14, 19 21, 12 29" fill="none" stroke="var(--text-faint)" strokeWidth=".8" opacity=".3" />
    </svg>
  )
}

// #6 — the pencil underline sketched under a task title on hover.
export function PencilUnderline() {
  return (
    <svg className="pencil-ul" viewBox="0 0 120 5" preserveAspectRatio="none" aria-hidden="true">
      <path
        d="M1 3.2 C 18 1.6, 34 4.2, 52 2.4 S 88 4, 104 2.2 L 118 3"
        fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" opacity=".75"
      />
      <path
        d="M3 4 C 22 2.6, 40 4.6, 60 3.2 S 96 4.4, 116 3.4"
        fill="none" stroke="currentColor" strokeWidth=".9" strokeLinecap="round" opacity=".4"
      />
    </svg>
  )
}
