// Hand-drawn die-cut sticker characters.
//
// These deliberately sit OUTSIDE the theme token system — the colours are
// hard-coded so the stickers stay exactly as warm and colourful in light mode
// as in dark. They are the one place in the app that breaks the design system
// on purpose: they should feel drawn by a person and stuck onto the timeline,
// not generated by it.
//
// Every character takes `hovered` and nudges one or two of its own details in
// response, so the reaction feels characterful rather than a generic scale-up.

const CREAM = '#FFF8EE'
const BLUSH = '#F58FA8'

// shared: thick cream underlay = the die-cut edge, drawn beneath the fill
function DieCut({ d, fill, ink, strokeWidth = 2.6 }) {
  return (
    <>
      <path d={d} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
      <path d={d} fill={fill} stroke={ink} strokeWidth={strokeWidth} strokeLinejoin="round" />
    </>
  )
}

const ease = 'transform .45s cubic-bezier(0.34, 1.56, 0.64, 1)'

export function SleepyBlob({ size = 84, hovered = false }) {
  const body = 'M34 10c10-1 20 5 23 14 3 10-2 21-11 26-9 5-21 3-27-4-6-7-7-19-1-27 4-6 10-8 16-9z'
  return (
    <svg viewBox="0 0 76 66" width={size} height={size * 0.87} aria-hidden="true">
      <g transform="rotate(-7 36 34)">
        <DieCut d={body} fill="#B9A7F0" ink="#2E2A33" />
        <ellipse cx="22" cy="38" rx="5" ry="3.2" fill={BLUSH} opacity=".6" />
        <ellipse cx="49" cy="38" rx="5" ry="3.2" fill={BLUSH} opacity=".6" />
        <path d="M21 31q4.5 5 9 0" fill="none" stroke="#2E2A33" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M41 31q4.5 5 9 0" fill="none" stroke="#2E2A33" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M32 40q4 3.5 8 0" fill="none" stroke="#2E2A33" strokeWidth="2.4" strokeLinecap="round" />
      </g>
      {/* the z's drift up when you look at it */}
      <g style={{ transform: hovered ? 'translate(2px,-5px)' : 'none', transition: ease }}>
        <path d="M60 20h7l-7 8h7" fill="none" stroke="#B9A7F0" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M64 7h5l-5 6h5" fill="none" stroke="#B9A7F0" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" opacity=".65" />
      </g>
    </svg>
  )
}

export function Snail({ size = 92, hovered = false }) {
  const foot = 'M8 47c0-7 5-11 12-11h30c5 0 9 2 9 5s-4 6-9 6H8z'
  return (
    <svg viewBox="0 0 78 60" width={size} height={size * 0.77} aria-hidden="true">
      {/* the whole snail inches forward */}
      <g transform="rotate(3 39 30)" style={{ transform: hovered ? 'translateX(3px)' : 'none', transition: ease }}>
        <DieCut d={foot} fill="#7FD8A8" ink="#26332C" />
        <circle cx="29" cy="26" r="15" fill={CREAM} stroke={CREAM} strokeWidth="9" />
        <circle cx="29" cy="26" r="15" fill="#F5D06B" stroke="#26332C" strokeWidth="2.6" />
        <path d="M29 26a5 5 0 1 1 5-5 9.5 9.5 0 1 1-9.5 9.5" fill="none" stroke="#26332C" strokeWidth="2.2" strokeLinecap="round" />
        <path d="M53 37l2-9M59 38l6-7" stroke="#26332C" strokeWidth="2.4" strokeLinecap="round" />
        <circle cx="55.5" cy="26" r="2.7" fill="#26332C" />
        <circle cx="66" cy="30" r="2.7" fill="#26332C" />
        <path d="M52 43q3.5 2.5 7 0" fill="none" stroke="#26332C" strokeWidth="2.2" strokeLinecap="round" />
      </g>
    </svg>
  )
}

export function CatLoaf({ size = 84, hovered = false }) {
  const loaf = 'M8 49c0-14 9-23 26-23s26 9 26 23z'
  const ears = 'M15 33l1-12 10 7zM53 33l-1-12-10 7z'
  return (
    <svg viewBox="0 0 72 60" width={size} height={size * 0.83} aria-hidden="true">
      <g transform="rotate(-4 36 30)">
        {/* papers it is sitting on — the tail flicks over them */}
        <g style={{ transform: hovered ? 'rotate(-7deg)' : 'none', transformOrigin: '44px 48px', transition: ease }}>
          <path d="M42 50h16l-4-7h-14z" fill={CREAM} stroke={CREAM} strokeWidth="7" />
          <path d="M42 50h16l-4-7h-14z" fill="#F0EAD8" stroke="#33302A" strokeWidth="2.2" strokeLinejoin="round" />
        </g>
        <path d={ears} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
        <path d={loaf} fill={CREAM} stroke={CREAM} strokeWidth="9" strokeLinejoin="round" />
        <path d={ears} fill="#F5B06B" stroke="#33302A" strokeWidth="2.5" strokeLinejoin="round" />
        <path d={loaf} fill="#F5B06B" stroke="#33302A" strokeWidth="2.6" strokeLinejoin="round" />
        <path d="M21 39q4 4.5 8 0M39 39q4 4.5 8 0" fill="none" stroke="#33302A" strokeWidth="2.5" strokeLinecap="round" />
        <path d="M34 43l-2.5 3h5z" fill={BLUSH} stroke="#33302A" strokeWidth="1.6" strokeLinejoin="round" />
        <path d="M12 41H4M12 46l-8 2M56 41h8M56 46l8 2" stroke="#33302A" strokeWidth="1.8" strokeLinecap="round" opacity=".8" />
      </g>
    </svg>
  )
}

export function Ghost({ size = 78, hovered = false }) {
  const body = 'M13 49V27a19 19 0 0 1 38 0v22l-6.3-5.3-6.4 5.3-6.3-5.3-6.4 5.3z'
  return (
    <svg viewBox="0 0 64 62" width={size} height={size * 0.97} aria-hidden="true">
      {/* bobs up when noticed */}
      <g transform="rotate(5 32 31)" style={{ transform: hovered ? 'translateY(-4px)' : 'none', transition: ease }}>
        <DieCut d={body} fill="#8FC7F5" ink="#25303B" />
        <circle cx="25" cy="28" r="3.1" fill="#25303B" />
        <circle cx="40" cy="28" r="3.1" fill="#25303B" />
        <ellipse cx="19" cy="35" rx="4.2" ry="2.7" fill={BLUSH} opacity=".6" />
        <ellipse cx="46" cy="35" rx="4.2" ry="2.7" fill={BLUSH} opacity=".6" />
        <path d="M29 35q3.5 3.5 7 0" fill="none" stroke="#25303B" strokeWidth="2.3" strokeLinecap="round" />
      </g>
    </svg>
  )
}

export function PartyBean({ size = 92, hovered = false }) {
  const body = 'M38 14c11 0 19 8 19 19s-8 20-19 20-19-9-19-20 8-19 19-19z'
  return (
    <svg viewBox="0 0 78 66" width={size} height={size * 0.85} aria-hidden="true">
      <g style={{ transform: hovered ? 'scale(1.12)' : 'none', transformOrigin: '39px 20px', transition: ease }}>
        <path d="M20 8l-3 7M60 12l5-5M68 30l7 1M12 26l-7-2" stroke={BLUSH} strokeWidth="2.6" strokeLinecap="round" />
        <rect x="58" y="44" width="7" height="7" rx="1.5" fill="#7FD8A8" transform="rotate(25 61 47)" />
        <rect x="10" y="42" width="6" height="6" rx="1.5" fill="#8FC7F5" transform="rotate(-20 13 45)" />
      </g>
      <g transform="rotate(-5 39 36)">
        <DieCut d={body} fill={BLUSH} ink="#3B2630" />
        <path d="M28 30q3.5-5 7 0M42 30q3.5-5 7 0" fill="none" stroke="#3B2630" strokeWidth="2.6" strokeLinecap="round" />
        <path d="M31 38q7 7 14 0" fill="none" stroke="#3B2630" strokeWidth="2.6" strokeLinecap="round" />
        <ellipse cx="25" cy="37" rx="4" ry="2.6" fill="#E0683C" opacity=".5" />
        <ellipse cx="51" cy="37" rx="4" ry="2.6" fill="#E0683C" opacity=".5" />
      </g>
    </svg>
  )
}

export function HappyStar({ size = 88, hovered = false }) {
  const body = 'M35 8l8 16 18 2-13 12 4 18-17-9-17 9 4-18L9 26l18-2z'
  return (
    <svg viewBox="0 0 70 66" width={size} height={size * 0.94} aria-hidden="true">
      <g transform="rotate(6 35 34)" style={{ transform: hovered ? 'rotate(14deg)' : 'none', transformOrigin: '35px 34px', transition: ease }}>
        <path d={body} fill={CREAM} stroke={CREAM} strokeWidth="10" strokeLinejoin="round" />
        <path d={body} fill="#F5D06B" stroke="#3A3320" strokeWidth="2.6" strokeLinejoin="round" />
        <circle cx="28" cy="31" r="2.8" fill="#3A3320" />
        <circle cx="42" cy="31" r="2.8" fill="#3A3320" />
        <path d="M30 38q5 5 10 0" fill="none" stroke="#3A3320" strokeWidth="2.4" strokeLinecap="round" />
        <ellipse cx="23" cy="37" rx="3.6" ry="2.3" fill={BLUSH} opacity=".55" />
        <ellipse cx="47" cy="37" rx="3.6" ry="2.3" fill={BLUSH} opacity=".55" />
      </g>
    </svg>
  )
}

// Waiting-pile cast. Order is stable — a pile hashes its day key into this
// array so the same day always gets the same character (it should read as
// someone who showed up, not a random shuffle every render).
export const WAITING = [
  { Art: SleepyBlob, rest: -7, label: 'napping' },
  { Art: Snail, rest: 3, label: 'taking their time' },
  { Art: CatLoaf, rest: -4, label: 'under the cat' },
  { Art: Ghost, rest: 5, label: 'gently haunting' },
]

// A per-session salt so the cast actually rotates on reload/reopen. Hashing the
// day key alone meant a given day ALWAYS drew the same character — stable, but
// in practice you only ever saw one of them. The salt is fixed for the life of
// the tab, so a character still can't shuffle out from under you mid-session.
const SESSION_SALT = Math.floor(Math.random() * WAITING.length)

export function pickWaiting(seed = '') {
  let h = 0
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0
  return WAITING[(h + SESSION_SALT) % WAITING.length]
}
